[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:server]
command=/bin/bash -c "cd /apps/server && exec dotnet %(ENV_SERVER_DLL)s"
autostart=false
autorestart=false
stdout_logfile=/logs/server-stage-%(ENV_STAGE)s.log
stderr_logfile=/logs/server-stage-%(ENV_STAGE)s.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=DOTNET_CLI_TELEMETRY_OPTOUT=1

[program:client]
command=/bin/bash -c "cd /apps/client && exec dotnet %(ENV_CLIENT_DLL)s"
autostart=false
autorestart=false
stdout_logfile=/logs/client-stage-%(ENV_STAGE)s.log
stderr_logfile=/logs/client-stage-%(ENV_STAGE)s.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=DOTNET_CLI_TELEMETRY_OPTOUT=1

[inet_http_server]
port=127.0.0.1:9001

[supervisorctl]
serverurl=http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
